### ISSUE TITLE
simssadb dump is not consistent with db.simssa.ca

### ISSUE THREAD

**Issue by malajvan** [malajvan/linkedmusic-datalake#1]
Currently, we're using Rebecca's database dump, which has more data than the actual db.simssa.ca website. This might cause confusion, furthermore, the file ID won't be correct so the URL from the flattening won't point to the right files. 
This is not an immediate problem but should be addressed soon before presenting it to others. 
The fix is simple by just replace the old dump with the latest dump from Simssadb

**Comment by dchiller** [comment]
@malajvan I think this is the same issues as what we were just talking about?

**Comment by malajvan** [comment]
@dchiller yes!

**Comment by malajvan** [comment]
@dchiller the newest dump file and generated json-ld in this repo now correspond to the current db.simssa.ca
